FROM golang:1.22-alpine

# Install Air
RUN go install github.com/cosmtrek/air@v1.44.0

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

COPY . .

WORKDIR /app/services/category

# Buat file .air.toml menggunakan heredoc
RUN <<'EOF' cat > .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "tests"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
EOF

# Create start.sh file
COPY <<EOF /start.sh
#!/bin/sh

# Menunggu service auth siap
until nc -z postgres 5432; do
  echo "Waiting for postgresql to be ready..."
  sleep 2
done
echo "postgresql is ready!"

air
EOF

RUN chmod +x /start.sh

CMD ["/start.sh"]